# Integrated Musicianship: A Theory and Aural Skills Method
# OER Music text book, by Sean Butterfield and Miranda Wilson

# jekyll theme adapted from Lanyon, https://github.com/poole/lanyon
# by evanwill

# site info
title: "Integrated Aural Skills"
tagline: "2018-19"
description: "an open, interactive, online textbook for college music theory"
keywords: "music theory, OER, university of idaho, inquiry-based"
owner: Miranda Wilson
email: mirandaw@uidaho.edu
published: 2018
github-repo: https://github.com/intmus/intas18-19

# urls
url: https://intmus.github.io
baseurl: /intas18-19

# collections
# each unit of the book is a collection
# each unit collection should be given a name value
collections:
  00-welcome:
    output: true
    name: Welcome
  01-introduction-to-intervals:
    output: true
    name: Introduction to Intervals
  02-introduction-to-diatonicism:
    output: true
    name: Introduction to Diatonicism
  03-introduction-to-melodic-dictation:
    output: true
    name: Introduction to Melodic Dictation
  04-introduction-to-seventh-chords:
    output: true
    name: Introduction to Seventh Chords
  05-working-with-intervals:
    output: true
    name: Working With Intervals
  06-building-fluency-in-melodic-dictation:
    output: true
    name: Building Fluency in Melodic Dictation
  07-increasingly-complex-rhythms:
    output: true
    name: Increasingly Complex Rhythms
  08-review-of-concepts:
    output: true
    name: Review of Concepts
  09-introduction-to-harmonic-dictation:
    output: true
    name: Introduction to Harmonic Dictation
  10-hearing-harmony:
    output: true
    name: Hearing Harmony
  11-length-and-complexity-in-melody-and-harmony:
    output: true
    name: Length and Complexity in Melody and Harmony
  12-modes-and-syncopations:
    output: true
    name: Modal Scales, Syncopated Rhythms
  13-strategies-for-recognition-and-error-detection:
    output: true
    name: Strategies for Recognition and Error Detection
  14-mastery-and-consolidation:
    output: true
    name: Mastery and Consolidation
  15-hearing-music-from-the-page:
    output: true
    name: Hearing Music from the Page
    
  
    

# ignore stuff
exclude: [docs]
